apiVersion: batch/v1
kind: Job
metadata:
  name: cenet-seg-job
spec:
  template:
    metadata:
      labels:
        k8s-app: cenet-seg-job
    spec:
      restartPolicy: Never
      containers:
        - name: cenet-seg-job
          image: ghcr.io/mraysu/mraysu_app:v4
          command:
            [
              "/bin/bash",
              "-c",
              "python -c 'import sys; print(sys.prefix)' && sh train.sh 0.75",
            ]
          volumeMounts:
            - mountPath: /root/dataset
              name: ivannia-volume
            - mountPath: /dev/shm
              name: cache-volume
          resources:
            limits:
              nvidia.com/gpu: "1"
              memory: "32G"
              cpu: "1"
              ephemeral-storage: "32G"
            requests:
              memory: "32G"
              cpu: "1"
              ephemeral-storage: "32G"
      volumes:
        - name: ivannia-volume
          persistentVolumeClaim:
            claimName: ivannia-volume
        - emptyDir:
            medium: Memory
            sizeLimit: 6G
          name: cache-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-A10
