apiVersion: apps/v1
kind: Deployment
metadata:
  name: cylinder-seg-sk
  labels:
    k8s-app: cylinder-seg-sk
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cylinder-seg-sk
  template:
    metadata:
      labels:
        k8s-app: cylinder-seg-sk
    spec:
      containers:
        - name: cylinder-seg-pod
          image: ghcr.io/darthiv02/cylinder3d_image:1.3
          command: ["sleep", "infinity"]
          volumeMounts:
            - mountPath: /root/dataset
              name: ivannia-volume
            - mountPath: /dev/shm
              name: cache-volume
          resources:
            limits:
              nvidia.com/gpu: "1"
              memory: "64G"
              cpu: "1"
              ephemeral-storage: "64G"
            requests:
              memory: "64G"
              cpu: "1"
              ephemeral-storage: "64G"
      volumes:
        - name: ivannia-volume
          persistentVolumeClaim:
            claimName: ivannia-volume
        - emptyDir:
            medium: Memory
            sizeLimit: 6G
          name: cache-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-A10
                    #- Tesla-V100-SXM2-32GB
