apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqn-seg-ms
  labels:
    k8s-app: sqn-seg-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sqn-seg-ms
  template:
    metadata:
      labels:
        k8s-app: sqn-seg-ms
    spec:
      containers:
        - name: sqn-seg-pod-ms
          image: ghcr.io/darthiv02/sqn_model_complete:1.2
          command: ["sleep", "infinity"]
          volumeMounts:
            - mountPath: /root/dataset
              name: tls-data-ivannia
          resources:
            limits:
              nvidia.com/gpu: "1"
              memory: "16G"
              cpu: "1"
            requests:
              memory: "16G"
              cpu: "1"
      volumes:
        - name: tls-data-ivannia
          persistentVolumeClaim:
            claimName: tls-data-ivannia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-GTX-1080-Ti
